version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_ENV: development
    networks:
      - backend-network  # Connect to backend network

networks:
  backend-network:
    external: true      # Use existing Docker network created by backend service
